#include<iostream>
#include<string>
using namespace std;

int main()
{
    int i, key;
    string CC_Encr, CC_Decr;
    
    cout << "Enter the key: ";
    cin >> key; //The key is 14 to crack the cipher
    
    cout << "Enter the message to decrypt: ";
    cin >> CC_Encr;
    /* Please copy and paste the following: HVSDFCXSQHUIHSBPSFUSPCCYCTOSGCDGTOPZSGPMOSGCDHVWGSPCCYWGTCFHVSIGSCTOBMCBSOBMKVSFSWBHVSIBWHSRGHOHSGOBRACGHCHVSFDOFHGCTHVSKCFZROHBCQCGHOBRKWHVOZACGHBCFSGHFWQHWCBGKVOHGCSJSFMCIAOMQCDMWHUWJSWHOKOMCFFSIGSWHIBRSFHVSHSFAGCTHVSDFCXSQHUIHSBPSFUZWQSBGSWBQZIRSRKWHVHVWGSPCCYCFCBZWBSOHKKKUIHSBPSFUCFUWTMCIOFSBCHZCQOHSRWBHVSIBWHSRGHOHSGMCIKWZZVOJSHCQVSQYHVSZOKGCTHVSQCIBHFMKVSFSMCIOFSZCQOHSRPSTCFSIGWBUHVWGSPCCYHWHZSOSGCDGTOPZSGOIHVCFOSGCDHFOBGZOHCFUSCFUSTMZSFHCKBGSBRFSZSOGSROHSXIBSSPCCYACGHFSQSBHZMIDROHSRCQHCPSFZOBU
     
     */
    
    for(i = 0; i < CC_Encr.size(); i++)
    {
        CC_Decr += (CC_Encr[i] - 'A' - key + 26) % 26 +'A';
    }
    cout << "\nDecrypted message is "<< CC_Decr <<'\n';
    
    return 0;
}
